name: Deploy S3
on:
  push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Deploy  # S3にデプロイ 
        env:
          S3_REGION: 'us-west-2'
          S3_BUCKET: 's3.orange-village.com'
          SOURCE_DIR: '.'
        run: |
          aws s3 sync --delete --region ${{env.S3_REGION}} ${{env.SOURCE_DIR}} s3://${{env.S3_BUCKET}}/ --exclude '.*git*'
